"""create guardrails_response and agent_response tables

Revision ID: a5c7d56c5390
Revises: 
Create Date: 2025-08-05 16:04:08.060665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5c7d56c5390'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_response',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('response_id', sa.String(), nullable=True),
    sa.Column('message_content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_agent_response_session_id'), 'agent_response', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_response_user_id'), 'agent_response', ['user_id'], unique=True)
    op.create_table('guardrails_response',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('toxicity', sa.JSON(), nullable=True),
    sa.Column('bias', sa.JSON(), nullable=True),
    sa.Column('ethics', sa.JSON(), nullable=True),
    sa.Column('pii', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('prompt_safety', sa.JSON(), nullable=True),
    sa.Column('tool_alignment', sa.JSON(), nullable=True),
    sa.Column('code_shield', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_guardrails_response_session_id'), 'guardrails_response', ['session_id'], unique=False)
    op.create_index(op.f('ix_guardrails_response_user_id'), 'guardrails_response', ['user_id'], unique=True)
    op.drop_table('project_versions')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('number_of_files', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extensions', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('fps', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('object_storage', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('minio_access_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('minio_secret_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('minio_endpoint_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bucket_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('mcp_configs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('project_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bucket_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("trigger = ANY (ARRAY['upload'::text, 'manual'::text])", name=op.f('project_versions_trigger_check')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_versions_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_versions_pkey'))
    )
    op.drop_index(op.f('ix_guardrails_response_user_id'), table_name='guardrails_response')
    op.drop_index(op.f('ix_guardrails_response_session_id'), table_name='guardrails_response')
    op.drop_table('guardrails_response')
    op.drop_index(op.f('ix_agent_response_user_id'), table_name='agent_response')
    op.drop_index(op.f('ix_agent_response_session_id'), table_name='agent_response')
    op.drop_table('agent_response')
    # ### end Alembic commands ###
